### ISSUE TITLE
Contact Log enhancement checklist

### ISSUE THREAD

**Issue by cheng-tan** [covidsafe/App-iOS#113]
#### Calendar component
- [x] it's jumpy on first time loading (#117)
- [x] Disable future days(#117)
- [x] Week view selected state(#117)

#### Locations
- [x] locations needs to be marked with dots in calendar (#114)
- [x] update default location page allow user import google history(#117)
- [ ] Allow add/edit/delete locations(tracked with #226 #228 )

###### Bugs:
- [ ] marked dot not showing in real time
- [ ] previous days location not show up 

#### People
- [x] Connect contact list with calendar (PR: #364 )
- [x] At least sort alphabetically
- [ ] Allow add new people
- [ ] If access is denied, show a link allow user to give access
- [ ] Add search(nice to have)
- [x] Loading contacts slow (#120)
- [ ] Update no contacts page
