### ISSUE TITLE
[Alert center] Reconcile V1 alerts tab with updated components

### ISSUE THREAD

**Issue by nessamilan** [covidsafe/App-iOS#338]
V1 designs are from April. Reconciliations need to be made to solve for the following:

- [ ] What does the UX look like when location logging is turned off?
- [ ] What new components need to be rolled into the timeline line items?
- [ ] How can a user share an alert?
- [ ] How can a user add an alert with time window to their calendar?
- [ ] How can the user search for alerts in other areas quickly?
- [ ] How does the user's live beacon behave?
- [ ] Alert pins: how can the styling be streamlined to increase accessibility and scalability? 

Connected to bug #83
